import pygame
import sys

level_map = [
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'DDD P                            DDD',
    'DDDDDDDDDDDDD                    DDD',
    'DDDXDDDXDDDDDXXDDD               DDD',
    'DDDDDDDDDDDDDDDDDDDDDDD          DDD',
    'DDDDDDDDDDDDXXXXDDDDDDDDDDD      DDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'DDD    1        DDDDDDD     DDD  DDD',
    'DDD             XXXXXXX          DDD',
    'XXX             DDDDXXD          DXX',
    'XXX             DDXXDDD          XDX',
    'DDD           DDDDXXXXXXDDDDDDDDDDDD',
    'DDD           DDDDDDDDDDDXXXXXXXXDDD',
    'DDD           DDDDDDDDDDDDDDDDDDDDDD',
    'XXX                              DDD',
    'DDD                              DDD',
    'DDD                              DDD',
    'DDDDDDDDDDDDDDDDDDDDDDDD      DDDDDD',
    'DDDDDDDDDDDDDDDDDDDDDDDD      DDDDDD',
    'DDD                              DDD',
    'DDD                              DDD',
    'DDD                              DDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                     1        DXD',
    'DDD        DDDDDDD               XDX',
    'DDD           DDDD               XDX',
    'DDD           DDDD               XDX',
    'DDDDDDD       DDDDDDDDD          XDX',
    'DDD           DDDDDDDDD          XDX',
    'DDD           DDDDDDDDD          XDX',
    'DDD           DDDDDDDDD          XDX',
    'DDD        DDDDDDDDDDDD          XDX',
    'DDD           DDDDDDDDD          XDX',
    'DDDDDDD       DDDDDDDDD          XDX',
    'DDD           DDDDDDDDD          XDX',
    'DDDDDDDDDDDDDDDDDDDDDDD          XDD',
    'DDDDDDDDDDDDDDDDDDDDDDD          DDD',
    'XDXXXXXXXXXXX                    DXD',
    'DDDDDDDDDDDDD                XXXXDDD',
    'DDDXDDDXDDDDDXXDDD               DDD',
    'DDDDDDDDDDDDDDDDDDDDDDD          DDD',
    'DDDDDDDDDDDDXXXXDDDDDDD          DDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX       1               XXXXXXXDXD',
    'XDX                       XXXXXXXDXD',
    'DDDD         DDDDDDDDDDDDDDXXXXXXXDD',
    'XDX                              DDD',
    'XDX                              DDD',
    'XDX                              DDD',
    'DDDDDDD            DDDD          DDD',
    'DDDD               XXXX          DDD',
    'XDX             DDDDXXD          DDD',
    'XDX           DDDDXXDDD          DDD',
    'DDD        DDDDDDDXXXXX         DDDD',
    'DDD    DDDDDDDDDDDDDDDD         XDDD',
    'DDDDDDDDDDDDDDDDDDDDDDD         DDDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'DDDDDDDDDDDDDDDDDDDDDDDD      DDDDDD',
    'DDDDDDDDDDDDDDDDDDDDDDDD      DDDDDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                     1        DXD',
    'DDD       DDDDDDDD               DDD',
    'DDD       DDDDDDDD               DDD',
    'DDD           DDDD               DDD',
    'DDDDDDD       DDDDDDDDDDDD       DDD',
    'DDD           DDDDDDDDDDDD       DDD',
    'DDD           DDDDDDDDDDDD       DDD',
    'XDX                              DXD',
    'DDDD                        DDDDDDDD',
    'DDDDDDDD                      DDDDDD',
    'DDDDDDDDDDDDD                    DDD',
    'DDDXDDDXDDDDDXXDDD               DDD',
    'DDDDDDDDDDDDDDDDDDDDDDD          DDD',
    'DDDDDDDDDDDDXXXXDDDDDDDDDDD      DDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'DDDD            DDDDDDD     DDD  DDD',
    'DDDD            XXXXXXX          DDD',
    'XXX             DDDDXXD          DXX',
    'XXX             DDXXDDD          XDX',
    'DDD           DDDDXXXXXXDDDDDDDDDDDD',
    'DDD           DDDDDDDDDDDXXXXXXXXDDD',
    'DDD           DDDDDDDDDDDDDDDDDDDDDD',
    'XXX                              DDD',
    'DDD                              DDD',
    'DDD                              DDD',
    'DDDDDDDDDDDDDDDDDDDDDDDD      DDDDDD',
    'DDDDDDDDDDDDDDDDDDDDDDDD      DDDDDD',
    'DDD                              DDD',
    'DDD                              DDD',
    'DDD                              DDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                      1       DXD',
    'DDD       DDDDDDDD               XDX',
    'DDD       DDDDDDDD               XDX',
    'DDD           DDDD               XDX',
    'DDDDDDD       DDDDDDDDD          XDX',
    'DDD           DDDDDDDDD          XDX',
    'DDD           DDDDDDDDD          XDX',
    'DDDDDDDDDDDDDDDDDDDDDDD          XDD',
    'DDDDDDDDDDDDDDDDDDDDDDD          DDD',
    'XDXXXXXXXXXXX                    DXD',
    'DDDDDDDDDDDDD                XXXXDDD',
    'DDDXDDDXDDDDDXXDDD               DDD',
    'DDDDDDDDDDDDDDDDDDDDDDD          DDD',
    'DDDDDDDDDDDDXXXXDDDDDDD          DDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                       XXXXXXXDXD',
    'XDX                     XXXXXXXXXDXD',
    'DDDDD        DDDDDDDDDDDDDDXXXXXXXDD',
    'XDX                              DDD',
    'XDX                              DDD',
    'XDX                              DDD',
    'XDX               DDDDDDD        DDD',
    'DDDDDDDDDDD       DDDDDDD        DDD',
    'DDDD            XXXXXXX          DDD',
    'XDX             DDDDXXD          DDD',
    'XDX             DDXXDDD          DDD',
    'DDD           DDDDXXXXXXDD     DDDDD',
    'DDD           DDDDDDDDDDDX     XXDDD',
    'DDD           DDDDDDDDDDDD     DDDDD',
    'XDX      DDDDDDDDDDD             DXD',
    'XDX     DDDDDDDDDDDD             DXD',
    'XDX     DDDDDDDDDDDD             DXD',
    'DDDDDDDDDDDDDDDDDDDDDDDD      DDDDDD',
    'DDDDDDDDDDDDDDDDDDDDDDDD      DDDDDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'DDDDDD       DDDDDDDDDDDDDDDDDDDDDDD',
    'XDX                              DXD',
    'XDX                   1          DXD',
    'XDX                              DXD',
    'DDD       DDDDDDDD               DDD',
    'DDD       DDDDDDDD               DDD',
    'DDD           DDDD               DDD',
    'DDDDDDD       DDDDDDDDDDDD       DDD',
    'DDD           DDDDDDDDDDDD       DDD',
    'DDD           DDDDDDDDDDDD       DDD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                              DXD',
    'XDX                           E  DXD',
    'XDX                              DXD',
    'XDXXDXDDXDXDXDXDDXDXDDXDXDXDXDDDXDXD',
    'XDXXDXDDXDXDXDXDDXDXDDXDXDXDXDDDXDXD',
    'XDXXDXDDXDXDXDXDDXDXDDXDXDXDXDDDXDXD',
    'XDXXDXDDXDXDXDXDDXDXDDXDXDXDXDDDXDXD',
    'XDXXDXDDXDXDXDXDDXDXDDXDXDXDXDDDXDXD',
    '                                    ''                                                                                                                                                                         ',
]

tile_size = 30
w = 1000
h = 600